apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: n8n-pg
  namespace: n8n-prod
  labels:
    environment: production
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: n8n
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: n8n-pg
  podMetricsEndpoints:
    - port: metrics
